### ISSUE TITLE
Update configuration of SwiftLint rule `attributes`

### ISSUE THREAD

**Issue by svenmuennich** [pickware/style-guide#55]
We currently use the SwiftLint rule `attributes` with its default configuration:
```yml
attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
  always_on_line_above: []
```

To make the code more consistent, the attributes `@IBAction` and `@NSManaged` should not be configured to always be on the same line as the declaration.
